const sharedRules = {
  "array-callback-return": "error",
  "block-scoped-var": "error",
  curly: ["error", "all"],
  eqeqeq: ["error", "always"],
  "no-alert": "error",
  "no-console": "error",
  "no-constant-binary-expression": "error",
  "no-duplicate-imports": "error",
  "no-else-return": "error",
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-implicit-coercion": "error",
  "no-irregular-whitespace": "error",
  "no-lone-blocks": "error",
  "no-loss-of-precision": "error",
  "no-new-native-nonconstructor": "error",
  "no-promise-executor-return": "error",
  "no-redeclare": "error",
  "no-self-compare": "error",
  "no-shadow-restricted-names": "error",
  "no-template-curly-in-string": "error",
  "no-unassigned-vars": "error",
  "no-undef": "error",
  "no-unmodified-loop-condition": "error",
  "no-unreachable-loop": "error",
  "no-unused-expressions": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
  "no-use-before-define": ["error", { functions: false }],
  "no-useless-assignment": "error",
  "no-useless-backreference": "error",
  "object-shorthand": ["error", "always"],
  "prefer-const": "error",
  "prefer-template": "error",
  radix: "error",
  "require-atomic-updates": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

module.exports = [
  {
    ignores: ["**/node_modules/**"],
  },
  {
    files: ["apps/web/src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        clearInterval: "readonly",
        document: "readonly",
        globalThis: "readonly",
        module: "readonly",
        window: "readonly",
      },
    },
    rules: sharedRules,
  },
  {
    files: ["apps/web/tests/**/*.js", "eslint.config.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        module: "readonly",
        require: "readonly",
      },
    },
    rules: sharedRules,
  },
  {
    files: ["scripts/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        Buffer: "readonly",
        URL: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        __dirname: "readonly",
        module: "readonly",
        process: "readonly",
        require: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: {
      ...sharedRules,
      "no-console": "off",
    },
  },
];
